development:
  adapter: postgresql
  database: product_finder_development
  pool: 5
  host: localhost
  port: 5432
  template: template0

test:
  adapter: postgresql
  database: product_finder_test
  pool: 5
  host: localhost
  port: 5432
  template: template0

production:
  adapter: postgresql
  database: product_finder_production
  pool: 5
  host: localhost
  port: 5432
  template: template0